include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_print
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - no_duplicate_case_values
    - unnecessary_statements
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_unnecessary_containers
    - avoid_shadowing_type_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cast_nullable_to_non_nullable
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_constructor_bodies
    - file_names
    - exhaustive_cases
    - implementation_imports
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - prefer_const_constructors
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_final_fields
    - require_trailing_commas
    - sort_child_properties_last
    



analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "lib/presentation/page/rig_details/widget/rig_details_menu_shape.dart"
    - "lib/di/injectible_init.config.dart"