name: flutter_mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  get_it: ^7.7.0
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.5
  infinite_scroll_pagination: ^4.0.0
  firebase_core: ^3.1.0
  mailer: ^6.1.0
  sqflite: ^2.3.3+1
  firebase_messaging: ^15.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1

dependency_overrides:
  intl: 0.19.0 

flutter:

  uses-material-design: true
